service: serverless-dio
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
          Resource:
            - arn:aws:dynamodb:sa-east-1:088457286732:table/serverless-dio-table
functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
  createItem:
    handler: src/createItem.handler
    events:
      - http:
          path: /item
          method: post
  readItems:
    handler: src/readItems.handler
    events:
      - http:
          path: /items
          method: get
  readItem:
    handler: src/readItem.handler
    events:
      - http:
          path: /items/{id}
          method: get
  updateItem:
    handler: src/updateItem.handler
    events:
      - http:
          path: /items/{id}
          method: put
resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: serverless-dio-table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
